const AppointmentActionTypes = {
  BOOK_APPOINTMENT: 'BOOK_APPOINTMENT',
  GET_APPOINTMENTS_START: 'GET_APPOINTMENTS_START',
  GET_APPOINTMENTS_SUCCESS: 'GET_APPOINTMENTS_SUCCESS',
  SET_IS_lOADING: 'SET_IS_lOADING',
};

export default AppointmentActionTypes;
