require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'practx_Mobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  # Tempoary
  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'practx_MobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' }, configurations: ['Debug', 'Staging'])
  #use_flipper!({ 'Flipper-Folly' => '2.3.0'}) #To fix build error
  # you should disable the next line.
  use_flipper!()
  
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'practx_Mobile-tvOS' do
  # Pods for practx_Mobile-tvOS

  target 'practx_Mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
