require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'practx_Mobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  target 'practx_MobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' }, configurations: ['Debug', 'Staging'])
  use_flipper!({ 'Flipper-Folly' => '2.3.0'}) #To fix build error
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'practx_Mobile-tvOS' do
  # Pods for practx_Mobile-tvOS

  target 'practx_Mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
