const SettingsActionTypes = {
  SET_THEME: 'SET_THEME',
  ON_SCROLL: 'ON_SCROLL',
  SPEED_DOWNLOAD_ACTIVE: 'SPEED_DOWNLOAD_ACTIVE',
  NET_STATE: 'NET_STATE',
  PLAY_SOUND: 'PLAY_SOUND',
  SOUND_ALERT: 'SOUND_ALERT',
  SHOW_NET_STATE: 'SHOW_NET_STATE',
  SHOW_DOWNLOAD_NOTIFY: 'SHOW_DOWNLOAD_NOTIFY',
  SHOW_MUSIC_NOTIFY: 'SHOW_MUSIC_NOTIFY',
  DOWNLOAD_STORAGE: 'DOWNLOAD_STORAGE',
  SHOW_INTRO: 'SHOW_INTRO',
  SET_FIRST_LUNCH: 'SET_FIRST_LUNCH',
  GET_MONT: 'GET_MONT',
  SET_MONT: 'SET_MONT',
  SET_WP_STAT: 'SET_WP_STAT',
};

export default SettingsActionTypes;
