const SettingsActionTypes = {
  CLEAR_PRACTICE_DATA: 'CLEAR_PRACTICE_DATA',

  GET_ALL_PRACTICES_START: 'GET_ALL_PRACTICES_START',
  GET_ALL_PRACTICES_SUCCESS: 'GET_ALL_PRACTICES_SUCCESS',
  GET_ALL_PRACTICES_FAILURE: 'GET_ALL_PRACTICES_FAILURE',
  GET_JOIN_PRACTICES_START: 'GET_JOIN_PRACTICES_START',
  GET_JOIN_PRACTICES_SUCCESS: 'GET_JOIN_PRACTICES_SUCCESS',

  GET_PRACTICES_DMS_START: 'GET_PRACTICES_DMS_START',
  GET_PRACTICES_DMS_SUCCESS: 'GET_PRACTICES_DMS_SUCCESS',
  JOIN_PRACTICES: 'JOIN_PRACTICES',

  SET_PRACTICE_ID: 'SET_PRACTICE_ID',
  SET_LOADING: 'SET_LOADING',
  SET_FILTER: 'SET_FILTER',
};

export default SettingsActionTypes;
