const SettingsActionTypes = {
  GET_ALL_PRACTICES_START: 'GET_ALL_PRACTICES_START',
  GET_ALL_PRACTICES_SUCCESS: 'GET_ALL_PRACTICES_SUCCESS',
  GET_ALL_PRACTICES_FAILURE: 'GET_ALL_PRACTICES_FAILURE',
  GET_JOIN_PRACTICES_START: 'GET_JOIN_PRACTICES_START',
  GET_JOIN_PRACTICES_SUCCESS: 'GET_JOIN_PRACTICES_SUCCESS',
  JOIN_PRACTICES: 'JOIN_PRACTICES',
  SET_LOADING: 'SET_LOADING',
  SET_FILTER: 'SET_FILTER',
};

export default SettingsActionTypes;
